repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.8.4'
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: ^src/api/client.js$
      - id: end-of-file-fixer
        exclude: ^src/api/client.js$
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
